# Generated by Django 5.0.1 on 2024-02-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PnoneNumbers',
            new_name='PhoneNumbers',
        ),
    ]
