# Generated by Django 5.0.1 on 2024-03-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_manager', '0003_delete_phonenumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('post_author', models.CharField(max_length=30)),
                ('post_name', models.CharField(max_length=100)),
                ('post_text', models.CharField(max_length=300)),
                ('post_date', models.CharField(max_length=100)),
                ('post_category', models.IntegerField()),
            ],
        ),
    ]
