# Generated by Django 5.0.1 on 2024-03-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_manager', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anon',
            name='post_id',
        ),
    ]
