# Generated by Django 5.0.1 on 2024-03-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_manager', '0009_alter_anon_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_post_id', models.IntegerField()),
                ('com_author', models.CharField(max_length=150)),
                ('com_text', models.CharField(max_length=250)),
                ('post_date', models.CharField(max_length=100)),
                ('com_category', models.IntegerField()),
                ('com_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
