# Generated by Django 5.0.1 on 2024-03-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_manager', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_date',
            new_name='com_date',
        ),
    ]
